sonarr-1080:

global:
  domain: "williamchambless.com"

  hostname: "sonarr-1080.CHANGE_ME_DOMAIN"

  replicaCount: 1

  namespace: "arr"

  config:
    xml:
      config.xml: |
        <Config>
          <BindAddress>*</BindAddress>
          <Port>8989</Port>
          <SslPort>9899</SslPort>
          <EnableSsl>False</EnableSsl>
          <LaunchBrowser>True</LaunchBrowser>
          <ApiKey>SONARR_1080_API_KEY_PLACEHOLDER</ApiKey>
          <AuthenticationMethod>None</AuthenticationMethod>
          <AuthenticationRequired>Enabled</AuthenticationRequired>
          <Branch>develop</Branch>
          <LogLevel>debug</LogLevel>
          <SslCertPath></SslCertPath>
          <SslCertPassword></SslCertPassword>
          <UrlBase></UrlBase>
          <InstanceName>Sonarr</InstanceName>
          <UpdateMechanism>Docker</UpdateMechanism>
          <PostgresUser>arruser</PostgresUser>
          <PostgresPassword>POSTGRES_PASSWORD_PLACEHOLDER</PostgresPassword>
          <PostgresPort>5432</PostgresPort>
          <PostgresHost>postgresql.arr.svc.cluster.local</PostgresHost>
          <PostgresMainDb>sonarr_1080_main</PostgresMainDb>
          <PostgresLogDb>sonarr_1080_log</PostgresLogDb>
        </Config>

  image:
    repository: "ghcr.io/linuxserver/sonarr"
    tag: "develop"
    pullPolicy: IfNotPresent

  env:
    puid: "1000"
    pgid: "1000"
    tz: "America/Chicago"

  service:
    type: ClusterIP
    port: 8989

  volumes:
    config:
      pvcName: "sonarr-1080-pvc"
      subPath: sonarr-1080
    series:
      pvcName: arr-series-pvc
    downloads:
      pvcName: arr-downloads-pvc

  healthcheck:
    startPeriod: 30
    interval: 30
    timeout: 5
    retries: 3

  resources:
    limits:
      memory: "1024Mi"  # Aligned with Radarr
      cpu: "1000m"
    requests:
      memory: "256Mi"
      cpu: "250m"

sonarr-4k:
  hostname: "sonarr-4k.CHANGE_ME_DOMAIN"
  replicaCount: 1
  namespace: "arr"

  config:
    xml:
      config.xml: |
        <Config>
          <BindAddress>*</BindAddress>
          <Port>8989</Port>
          <SslPort>9899</SslPort>
          <EnableSsl>False</EnableSsl>
          <LaunchBrowser>True</LaunchBrowser>
          <ApiKey>SONARR_4K_API_KEY_PLACEHOLDER</ApiKey>
          <AuthenticationMethod>None</AuthenticationMethod>
          <AuthenticationRequired>Enabled</AuthenticationRequired>
          <Branch>develop</Branch>
          <LogLevel>debug</LogLevel>
          <SslCertPath></SslCertPath>
          <SslCertPassword></SslCertPassword>
          <UrlBase></UrlBase>
          <InstanceName>Sonarr</InstanceName>
          <UpdateMechanism>Docker</UpdateMechanism>
          <PostgresUser>arruser</PostgresUser>
          <PostgresPassword>POSTGRES_PASSWORD_PLACEHOLDER</PostgresPassword>
          <PostgresPort>5432</PostgresPort>
          <PostgresHost>postgresql.arr.svc.cluster.local</PostgresHost>
          <PostgresMainDb>sonarr_4k_main</PostgresMainDb>
          <PostgresLogDb>sonarr_4k_log</PostgresLogDb>
        </Config>

  image:
    repository: "ghcr.io/linuxserver/sonarr"
    tag: "develop"
    pullPolicy: IfNotPresent

  env:
    puid: "1000"
    pgid: "1000"
    tz: "America/Chicago"

  service:
    type: ClusterIP
    port: 8989

  volumes:
    config:
      pvcName: "sonarr-4k-pvc"
      subPath: sonarr-4k
    series:
      pvcName: arr-series-pvc
    downloads:
      pvcName: arr-downloads-pvc

  healthcheck:
    startPeriod: 30
    interval: 30
    timeout: 5
    retries: 3

  resources:
    limits:
      memory: "1024Mi"
      cpu: "1000m"
    requests:
      memory: "256Mi"
      cpu: "250m"

