apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.image.pullSecret }}
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret }}
          {{- end }}
          initContainers:
            - name: init-config
              image: busybox
              command: 
              - sh
              - -c
              - |
                echo "Processing config with secret substitution..."
                # Substitute API key placeholders with actual secrets
                sed -e "s/SONARR_1080_API_KEY_PLACEHOLDER/$SONARR_1080_API_KEY/g" \
                    -e "s/SONARR_4K_API_KEY_PLACEHOLDER/$SONARR_4K_API_KEY/g" \
                    -e "s/RADARR_1080_API_KEY_PLACEHOLDER/$RADARR_1080_API_KEY/g" \
                    -e "s/RADARR_4K_API_KEY_PLACEHOLDER/$RADARR_4K_API_KEY/g" \
                    /tmp/config-template/config.yml > /shared/config.yml
                echo "Config processing completed"
              env:
                - name: SONARR_1080_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: app-api-keys
                      key: sonarr-1080-api-key
                - name: SONARR_4K_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: app-api-keys
                      key: sonarr-4k-api-key
                - name: RADARR_1080_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: app-api-keys
                      key: radarr-1080-api-key
                - name: RADARR_4K_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: app-api-keys
                      key: radarr-4k-api-key
              volumeMounts:
                - name: config-volume
                  mountPath: /tmp/config-template
                - name: shared-config
                  mountPath: /shared
          containers:
            - name: configarr
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              tty: true
              
              volumeMounts:
                - mountPath: /app/repos
                  name: app-data
                  subPath: configarr-repos
                - name: shared-config
                  mountPath: /app/config/config.yml
                  subPath: config.yml
          volumes:
            - name: app-data
              persistentVolumeClaim:
                claimName: {{ .Values.appDataPVC }}
            - name: config-volume
              configMap:
                name: configarr
            - name: shared-config
              emptyDir: {}
          restartPolicy: Never
