apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configarr-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: configarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-nvme
