replicaCount: 1

global:
  domain: "williamchambless.com"

namespace: web



image:
  repository: lscr.io/linuxserver/openvscode-server
  tag: latest
  pullPolicy: IfNotPresent

env:
  puid: "1000"
  pgid: "1000"
  tz: "America/Chicago"
  dockerMods: "linuxserver/mods:universal-docker|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-npmglobal"
  nodejsModVersion: "20"

service:
  type: ClusterIP
  port: 3010

hostname: "openvscode.CHANGE_ME_DOMAIN"

resources:
  limits:
    memory: "2Gi"
    cpu: "1000m"
  requests:
    memory: "512Mi"
    cpu: "250m"

healthcheck:
  enabled: true
  startPeriod: 30
  interval: 30
  timeout: 5
  retries: 3

persistence:
  config:
    enabled: true
    pvcName: openvscode-config-pvc
    storageClass: longhorn-nvme
    size: 10Gi
    mountPath: /config

# Secret references
