apiVersion: v1
kind: Service
metadata:
  name: {{ include "organizr.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "organizr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.main.type }}
  ports:
    - port: {{ .Values.service.main.ports.http.port }}
      targetPort: {{ .Values.service.main.ports.http.targetPort }}
      protocol: {{ .Values.service.main.ports.http.protocol }}
      name: http
  selector:
    {{- include "organizr.selectorLabels" . | nindent 4 }}