apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.config.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: sabnzbd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-nvme
