apiVersion: v1
kind: Service
metadata:
  name: {{ include "sabnzbd.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: sabnzbd
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sabnzbd
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
    name: webui
