bazarr-1080:
  replicaCount: 1
  namespace: "arr"

  config:
    yaml:
      config.yaml: |
        postgresql:
          database: bazarr_1080
          enabled: true
          host: postgresql.arr.svc.cluster.local
          password: POSTGRES_PASSWORD_PLACEHOLDER
          port: 5432
          username: arruser
        general:
          port: 6767
          ip: '*'
          base_url: ''
          branch: master
          auto_update: true
          debug: false

  image:
    repository: "ghcr.io/linuxserver/bazarr"
    tag: "latest"
    pullPolicy: IfNotPresent

  env:
    puid: "1000"
    pgid: "1000"
    tz: "America/Chicago"

  service:
    type: ClusterIP
    port: 6767

  volumes:
    config:
      pvcName: "bazarr-1080-pvc"
      subPath: bazarr-1080
    movies:
      pvcName: arr-movies-pvc
      # Removed subPath to mount entire PVC
    series:
      pvcName: arr-series-pvc
      # Removed subPath to mount entire PVC

  healthcheck:
    startPeriod: 30
    interval: 30
    timeout: 5
    retries: 3

  resources:
    limits:
      memory: "512Mi"
      cpu: "1000m"
    requests:
      memory: "256Mi"
      cpu: "250m"

bazarr-4k:
  replicaCount: 1
  namespace: "arr"

  config:
    yaml:
      config.yaml: |
        postgresql:
          database: bazarr_4k
          enabled: true
          host: postgresql.arr.svc.cluster.local
          password: POSTGRES_PASSWORD_PLACEHOLDER
          port: 5432
          username: arruser
        general:
          port: 6767
          ip: '*'
          base_url: ''
          branch: master
          auto_update: true
          debug: false

  image:
    repository: "ghcr.io/linuxserver/bazarr"
    tag: "latest"
    pullPolicy: IfNotPresent

  env:
    puid: "1000"
    pgid: "1000"
    tz: "America/Chicago"

  service:
    type: ClusterIP
    port: 6767

  volumes:
    config:
      pvcName: "bazarr-4k-pvc"
      subPath: bazarr-4k
    movies:
      pvcName: arr-movies-pvc
      # Removed subPath to mount entire PVC
    series:
      pvcName: arr-series-pvc
      # Removed subPath to mount entire PVC

  healthcheck:
    startPeriod: 30
    interval: 30
    timeout: 5
    retries: 3

  resources:
    limits:
      memory: "512Mi"
      cpu: "1000m"
    requests:
      memory: "256Mi"
      cpu: "250m"

# Secret references
# Domain configuration - override this value in Fleet
global:
  domain: "CHANGE_ME_DOMAIN"

postgres:
  password: 
    valueFrom:
      secretKeyRef:
        name: postgres-credentials
        key: password