apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sonarr.fullname" . }}
  namespace: {{ index .Values "sonarr-1080" "namespace" }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sonarr-1080.{{ .Values.global.domain }}
        - sonarr-4k.{{ .Values.global.domain }}
      secretName: sonarr-tls
  rules:
    - host: sonarr-1080.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr-1080
                port:
                  number: 8989
    - host: sonarr-4k.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr-4k
                port:
                  number: 8989
