apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: {{ .Values.namespace }}
  labels:
    app: prowlarr
spec:
  type: {{ .Values.service.type }}
  selector:
    app: prowlarr
  ports:
    - protocol: TCP
      port: 9696
      targetPort: 9696
      name: webui
