
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvscode
  namespace: {{ .Values.namespace }}
  labels:
    app: openvscode-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: openvscode-server
  template:
    metadata:
      labels:
        app: openvscode-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: node01
      containers:
      - name: openvscode-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
          name: webui
        env:
        - name: PUID
          value: "{{ .Values.env.puid }}"
        - name: PGID
          value: "{{ .Values.env.pgid }}"
        - name: TZ
          value: "{{ .Values.env.tz }}"
        - name: DOCKER_MODS
          value: "{{ .Values.env.dockerMods }}"
        - name: NODEJS_MOD_VERSION
          value: "{{ .Values.env.nodejsModVersion }}"
        volumeMounts:
        - name: config
          mountPath: {{ .Values.persistence.config.mountPath }}
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: appdata
          mountPath: /mnt/appdata
        {{- if .Values.healthcheck.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: {{ .Values.healthcheck.startPeriod }}
          periodSeconds: {{ .Values.healthcheck.interval }}
          timeoutSeconds: {{ .Values.healthcheck.timeout }}
          failureThreshold: {{ .Values.healthcheck.retries }}
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: {{ .Values.healthcheck.timeout }}
          failureThreshold: {{ .Values.healthcheck.retries }}
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 30
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.persistence.config.enabled }}
      - name: config
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.config.pvcName }}
      {{- else }}
      - name: config
        hostPath:
          path: /mnt/appdata/utilities/openvscode-server/config
      {{- end }}
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: appdata
        hostPath:
          path: /mnt/appdata
      restartPolicy: Always
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
