apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openvscode
  namespace: {{ .Values.namespace }}
  labels:
    app: openvscode-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - openvscode.{{ .Values.global.domain }}
      secretName: openvscode-tls
  rules:
    - host: openvscode.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openvscode
                port:
                  number: {{ .Values.service.port }}