apiVersion: v1
kind: Service
metadata:
  name: openvscode-server
  namespace: {{ .Values.namespace }}
  labels:
    app: openvscode-server
spec:
  selector:
    app: openvscode-server
  ports:
  - protocol: TCP
    port: 3010
    targetPort: 3000
    name: webui
  type: {{ .Values.service.type }}
