apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cleanuparr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cleanuparr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cleanuparr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cleanuparr.selectorLabels" . | nindent 8 }}
      annotations:
        diun.enable: "true"
        autoheal: "true"
    spec:
      securityContext:
        fsGroup: {{ .Values.env.pgid }}
      containers:
      - name: cleanuparr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        env:
        - name: PORT
          value: "{{ .Values.service.port }}"
        - name: PUID
          value: "{{ .Values.env.puid }}"
        - name: PGID
          value: "{{ .Values.env.pgid }}"
        - name: TZ
          value: "{{ .Values.env.tz }}"
        volumeMounts:
        - name: config
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.healthcheck.startPeriod }}
          periodSeconds: {{ .Values.healthcheck.interval }}
          timeoutSeconds: {{ .Values.healthcheck.timeout }}
          failureThreshold: {{ .Values.healthcheck.retries }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.healthcheck.startPeriod }}
          periodSeconds: {{ .Values.healthcheck.interval }}
          timeoutSeconds: {{ .Values.healthcheck.timeout }}
          failureThreshold: {{ .Values.healthcheck.retries }}
        startupProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 30
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.config.pvcName }}
      restartPolicy: Always
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
