apiVersion: v1
kind: Service
metadata:
  name: {{ include "cleanuparr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cleanuparr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cleanuparr.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: webui
