apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  rules:
    - host: qbittorrent.local  # Update this with your app name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "qbittorrent.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
