apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.config.pvcName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: qbittorrent
    release: {{ .Release.Name }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
