apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.config.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
