apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: {{ .Values.namespace }}
  labels:
    app: qbittorrent
spec:
  type: {{ .Values.service.type }}
  selector:
    app: qbittorrent
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: webui
  - protocol: TCP
    port: 6881
    targetPort: 6881
    name: torrent-tcp
  - protocol: UDP
    port: 6881
    targetPort: 6881
    name: torrent-udp