apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tdarr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - tdarr.{{ .Values.global.domain }}
      secretName: tdarr-tls
  rules:
    - host: tdarr.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tdarr.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
