apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdarr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "tdarr.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 8265
    targetPort: 8265
    name: webui
  - protocol: TCP
    port: 8266
    targetPort: 8266
    name: server
  type: {{ .Values.service.type }}
