apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  namespace: {{ .Values.tautulli.namespace }}
  labels:
    app: tautulli
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - tautulli.{{ .Values.global.domain }}
      secretName: tautulli-tls
  rules:
    - host: tautulli.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tautulli
                port:
                  number: {{ .Values.tautulli.service.port }}
