apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: {{ .Values.namespace }}
  labels:
    app: tautulli
spec:
  selector:
    app: tautulli
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: http
  type: {{ .Values.service.type }}
