{{- define "lidarr.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
      annotations:
        diun.enable: "true"
        autoheal: "true"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      {{- if .config }}
      - name: init-config
        image: busybox
        command: 
        - sh
        - -c
        - |
          echo "Checking source config..."
          ls -la /tmp/lidarr-config/
          echo "Source config content:"
          cat /tmp/lidarr-config/config.xml
          echo "Processing config with secret substitution..."
          # Always substitute environment variables in case secrets changed
          sed -e "s/POSTGRES_PASSWORD_PLACEHOLDER/$POSTGRES_PASSWORD/g" \
              -e "s/LIDARR_API_KEY_PLACEHOLDER/$LIDARR_API_KEY/g" \
              /tmp/lidarr-config/config.xml > /config/config.xml
          echo "Config updated with secret substitution. Verifying..."
          ls -la /config/config.xml
          echo "Destination content (secrets masked):"
          sed -e 's/<ApiKey>.*<\/ApiKey>/<ApiKey>[MASKED]<\/ApiKey>/g' \
              -e 's/<PostgresPassword>.*<\/PostgresPassword>/<PostgresPassword>[MASKED]<\/PostgresPassword>/g' \
              /config/config.xml
          echo "Secret substitution completed!"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: LIDARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-api-keys
              key: lidarr-api-key
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: {{ .volumes.config.subPath }}
        - name: lidarr-config
          mountPath: /tmp/lidarr-config
      {{- end }}
      containers:
      - name: lidarr
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - containerPort: 8686
          name: http
        env:
        - name: PUID
          value: "{{ .env.puid }}"
        - name: PGID
          value: "{{ .env.pgid }}"
        - name: TZ
          value: "{{ .env.tz }}"
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: {{ .volumes.config.subPath }}
        - name: music
          mountPath: /mnt/music
        - name: downloads
          mountPath: /mnt/downloads
        livenessProbe:
          httpGet:
            path: /
            port: 8686
          initialDelaySeconds: {{ .healthcheck.startPeriod }}
          periodSeconds: {{ .healthcheck.interval }}
          timeoutSeconds: {{ .healthcheck.timeout }}
          failureThreshold: {{ .healthcheck.retries }}
        startupProbe:
          httpGet:
            path: /
            port: 8686
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8686
          initialDelaySeconds: {{ .healthcheck.startPeriod }}
          periodSeconds: {{ .healthcheck.interval }}
          timeoutSeconds: {{ .healthcheck.timeout }}
          failureThreshold: {{ .healthcheck.retries }}
        resources:
          {{- toYaml .resources | nindent 12 }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: {{ .volumes.config.pvcName }}
      - name: music
        persistentVolumeClaim:
          claimName: {{ .volumes.music.pvcName }}
      - name: downloads
        persistentVolumeClaim:
          claimName: {{ .volumes.downloads.pvcName }}
      {{- if .config }}
      - name: lidarr-config
        configMap:
          name: lidarr-config
      {{- end }}
      restartPolicy: Always
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
{{- end }}

---

{{- with .Values }}
{{- include "lidarr.deployment" (dict 
  "name" "lidarr" 
  "namespace" .namespace 
  "replicaCount" .replicaCount 
  "image" .image 
  "env" .env 
  "volumes" .volumes
  "healthcheck" .healthcheck
  "resources" .resources
  "config" .config
) }}
{{- end }}
