apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lidarr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lidarr.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - lidarr.{{ .Values.global.domain }}
      secretName: lidarr-tls
  rules:
    - host: lidarr.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lidarr
                port:
                  number: 8686
